/*
 * This source file was generated by the Gradle 'init' task
 */
package pa4;

/** 
 *  A binary search tree (BST) is a binary tree where each node has 
 * a comparable key (and an associated value) and satisfies the restriction that 
 * the key in any node is larger than the keys in all nodes in that node's left subtree 
 * and smaller than the keys in all nodes in that node's right subtree.
 */
public class BST {
    
    public static class Node {
        public int value;
        public Node left;
        public Node right;

        public Node(int value) {
            this.value = value;
            this.left = null;
            this.right = null;
        }
    }

    public Node root;

    public BST() {
        this.root = null;
    }

    /** 
     * Insert a node with a given value into the BST.
     * @param value the value of the node to insert
     */
    public void insert(int value) {
        
        if (root ==null){
            this.root = new Node (value);
        }
        else{
        bs_recurr(root, value);
        }
    }
    private Node bs_recurr(Node root, int value){
        if (root ==null){
            root = new Node (value);
            return root;
        }
        else if(value<=root.value){
            root.left= bs_recurr(root.left, value);
        }
        else if(value>=root.value){
            root.right= bs_recurr(root.right, value);
        }
        return root;
    }


    /** 
     * Delete a node with a given value from the BST.
     * @param value the value of the node to delete
     */
    public void delete(int value) {
        if (!this.search(value)) {
            return;
        }
        this.root = delete_recurr(this.root, value);   
    }

    private Node delete_recurr(Node root, int value){
        if (root  == null){
            return null;
        }
        else if(value<root.value){
            root.left =  delete_recurr(root.left, value);
            
        }
        else if(value>root.value){
            root.right =  delete_recurr(root.right, value);
        }

        else{
            if (root.left == null & root.right == null){
                return null;
            }
            else if(root.left == null & root.right != null){
                return root.right;
            }
            else if(root.right == null & root.left != null){
                return root.left;
            }
            else{
                root.value = deleteHelper(root.right);
                root.right = delete_recurr(root.right, root.value);
            }
        }
        return root;

    }
    private int deleteHelper(Node root){
     
            while (root.left != null) {
                root = root.left;
            }
            return root.value;
        }
    


    /** 
     * Search for a node with a given value in the BST and return true if found.
     * @param value the value to search for
     */
    public boolean search(int value) {
        boolean answer = search_recurr(root, value);
        return answer;
        
    }

    private boolean search_recurr(Node root, int value){
        if (root  ==null){
            return false;
        }
        else if(value<root.value){
            return search_recurr(root.left, value);
            
        }
        else if(value>root.value){
            return search_recurr(root.right, value);
        }
        return true;
    }
    
    /** 
     * Update a node with a given old value to a new value in the BST.
     * @param oldValue the old value of the node to update
     * @param newValue the new value of the node to update
     */
    public void update(int oldValue, int newValue) {
        if (this.search(oldValue) == true) {
            this.delete(oldValue);
            this.insert(newValue);
        }
    }

    /** 
     * Traverse the BST in inorder and return the values as a string. 
     * @return the inorder traversal of the BST
     */
    public String inOrder() {
     
        return this.inOrderTraversalHelper(this.root);
    }
    private String inOrderTraversalHelper(Node curr){
       if (curr==null){
           return "";
       }
       String left = this.inOrderTraversalHelper(curr.left);
       String right = this.inOrderTraversalHelper(curr.right);
       return "" + left + curr.value + right;

    }

    /** 
     * Convert a sorted array to a balanced BST.
    //  */
    public static Node sortedArrayToBST(int[] arr) {
        return sortedArrayToBSTHelper(arr, 0, arr.length - 1);
    }

    private static Node sortedArrayToBSTHelper(int[] arr, int low, int high) {
        if (low > high) {
            return null;
        }
        int mid = (low + high) / 2;
        Node node = new Node(arr[mid]);
        node.left = sortedArrayToBSTHelper(arr, low, mid - 1);
        node.right = sortedArrayToBSTHelper(arr, mid + 1, high);
        return node;
    }

    // /** 
    //  * Find the lowest common ancestor of two nodes with given values in the BST.
    //  */
    public Node lowestCommonAncestor(int value1, int value2) {
        return lowestCommonAncestorHelper(this.root, value1, value2);
    }

    private Node lowestCommonAncestorHelper(Node curr, int value1, int value2) {
        if (curr == null) {
            return null;
        }
        if ((curr.value > value1) && (curr.value > value2)) {
            return lowestCommonAncestorHelper(curr.left, value1, value2);
        }
        if ((curr.value < value1) && (curr.value < value2)) {
            return lowestCommonAncestorHelper(curr.right, value1, value2);
        }
        return curr;
    }    


    public static void main(String[] args) {

        BST bst = new BST();
        bst.insert(5);
        bst.insert(3);
        bst.insert(7);
        bst.insert(2);
        System.out.println(bst.inOrder());
        bst.insert(4);
        bst.insert(6);
        bst.insert(8);
        System.out.println(bst.search(1));
        System.out.println(bst.inOrder());

        System.out.println(bst.inOrder());
        bst.delete(3);
        System.out.println(bst.inOrder());
        System.out.println(bst.search(3));
        System.out.println(bst.search(4));
        bst.update(4, 9);

        int[] arr = {1, 2, 3, 4, 5, 6, 7};
        Node root = BST.sortedArrayToBST(arr);
        System.out.println(root.value);

        System.out.println(bst.lowestCommonAncestor(2, 4).value);
        System.out.println(bst.lowestCommonAncestor(2, 6).value);

    }
}
